### ISSUE TITLE
css triangle

### ISSUE THREAD

**Issue by keepgagaga** [keepgagaga/records#113]
有时候会需要自己用一些css技巧画图形，比用图片来得方便，下面是一些图形的绘制技巧。

三角形：
```css
.triangleRight { // 箭头指向右侧的三角形，如果想指向某个方向，只需要将垂直方向的两条 border 设为透明，再将指向方向的对立面设为想要的颜色就好，宽高度根据自己的需要调。
    width: 0;
    height: 0;
    border-top: 3px solid transparent;
    border-bottom: 3px solid transparent;
    border-left: 6px solid #BCC1C5;
}
```
