### ISSUE TITLE
css mask

### ISSUE THREAD

**Issue by keepgagaga** [keepgagaga/records#115]
css 遮罩的实现有很多方法，但好多方法有限制，只能在简单场景里使用，目前实践下来最成熟简单的办法就是使用相对定位在页面上加一个新的相同大小的元素来实现遮罩。

```css
<div class='overlay'></div>
.overlay {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.6);
}
```
