### ISSUE TITLE
css 背景图模糊

### ISSUE THREAD

**Issue by Sand2Dev** [keepgagaga/records#84]
背景图模糊是个常见的需求，常见于一张背景图加上描述性文字，看到这个需求第一印象是直接在图上使用背景模糊，但用了之后会发现连背景图层之上的文字也模糊了，这显然不行，我们可以使用伪类的方法来实现这个效果。

```css
.bgImg {
  width: 100vw;
  height: 1080px;
  position: relative;
}

.bgImg::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100vw;
  height: 1080px;
  z-index: -1;
  background-image: url('/bgImg.png');
  background-size: cover;
  background-repeat: no-repeat;
  filter: blur(5px);
}
```
