### ISSUE TITLE
简单实现过渡效果

### ISSUE THREAD

**Issue by keepgagaga** [keepgagaga/records#91]
```html
<button class="transition-btn">按钮</button>
```
```css
.transition-btn {
    background-color: white;
    color: black;
    padding: 10px 20px;
    font-size: 16px;
    border: 1px solid black;
    transition-property: background-color; // 指定要过渡的属性
    transition-duration: 1s; //指定要过渡的时间
}

.transition-btn:hover {
    background-color: red; //触发过渡
}
```
